name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      message:
        description: 'Commit message for auto-fixes'
        required: false
        default: '🤖 Auto-fix linting issues'

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm init -y
        npm install --save-dev stylelint
        npm install --save-dev htmlhint
        
    - name: Create config files
      run: |
        echo '{
          "rules": {
            "no-duplicate-selectors": null,
            "no-descending-specificity": null,
            "no-invalid-position-at-import-rule": null
          }
        }' > .stylelintrc.json
        echo '{
          "tagname-lowercase": true,
          "attr-lowercase": true,
          "attr-value-double-quotes": true,
          "doctype-first": false
        }' > .htmlhintrc
        
    - name: Lint and fix
      run: |
        npx prettier --write "*.{html,css,js}" || true
        npx stylelint "**/*.css" --fix || true
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "${{ github.event.inputs.message || '🤖 Auto-fix linting issues' }}" && git push)

  deploy:
    needs: lint-and-fix
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: . 